name: 'Scripted kubernetes deployment'
description: 'Scripted kubernetes deployment with GitHub Actions'
branding:
  icon: activity
  color: green
author: 'Mats Törnberg'
inputs:
  secret:
    description: Encryption key
  configFile:
    description: Override config file 
  k8sConfig:
    description: 'Kubernetes config'
  scriptPath:
    description: "Path to the deployment to apply"
    default: 'deploy.js'
runs:
  using: node16
  main: lib/slask.js
