name: Test current version deploy
on: push

jobs:
  sonar:
    name: Test deploy action
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: sonarsource/sonarqube-scan-action@master
      name: Check code with sonarqube
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  deploy:
    name: Test deploy action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploy scripted application
        uses: ./
        with:
          k8sConfig: ${{secrets.K8S_CONFIG}}
          scriptPath: ./test-deployment.js
          secret: ${{secrets.CONFIG_KEY}}
