on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploy scripted application
        uses: ./
        with:
          k8sConfig: ${{secrets.K8S_CONFIG}}
          scriptPath: ./test-deployment.cjs
          secret: ${{secrets.CONFIG_KEY}}
